#!/bin/bash
# Auto-generated route + component census for the UI upgrade program.
cd /home/user/staybid-frontend
OUT=docs/upgrade/01-INVENTORY.md
{
echo "# 01 — Complete Surface Inventory (auto-generated)"
echo ""
echo "> Generated by \`docs/upgrade/gen-inventory.sh\`. Re-run after any route add/remove."
echo "> Generated: $(date -u +%Y-%m-%d)"
echo ""
echo "## A. Route census (every page.tsx, grouped by surface)"
echo ""
echo "| # | Route | Lines | Panel |"
echo "|---|---|---|---|"
i=0
find app -name "page.tsx" | sort | while read f; do
  i=$((i+1))
  route=$(dirname "$f" | sed 's|^app||; s|^$|/|')
  lines=$(wc -l < "$f")
  panel=$(echo "$route" | cut -d/ -f2)
  case "$panel" in
    admin|partner|circle|trade|worker|host|influencer|onboard|agent) p="$panel" ;;
    "") p="customer" ;;
    *) p="customer" ;;
  esac
  echo "| $i | \`${route:-/}\` | $lines | $p |"
done
echo ""
echo "## B. Component census"
echo ""
echo "| Folder | Files | Lines |"
echo "|---|---|---|"
for d in $(find components -maxdepth 1 -type d | sort); do
  files=$(find "$d" -maxdepth 1 -name "*.tsx" | wc -l)
  lines=$(find "$d" -maxdepth 1 -name "*.tsx" -exec cat {} + 2>/dev/null | wc -l)
  [ "$files" -gt 0 ] && echo "| \`$d\` | $files | $lines |"
done
echo ""
echo "## C. Stylesheet census"
echo ""
echo "| File | Lines |"
echo "|---|---|"
for f in $(find app -name "*.css" | sort); do
  echo "| \`$f\` | $(wc -l < "$f") |"
done
echo ""
echo "## D. Totals"
echo ""
echo "- Pages: $(find app -name 'page.tsx' | wc -l)"
echo "- Layouts: $(find app -name 'layout.tsx' | wc -l)"
echo "- API routes (DO NOT TOUCH in UI upgrade): $(find app/api -name 'route.ts' | wc -l)"
echo "- Components: $(find components -name '*.tsx' | wc -l)"
echo "- Total TSX lines: $(find app components -name '*.tsx' | xargs cat | wc -l)"
echo "- Total CSS lines: $(find app -name '*.css' | xargs cat | wc -l)"
} > "$OUT"
echo "written $OUT ($(wc -l < "$OUT") lines)"
