-- v112.1 — `highlight_key` lets server-side posts carry the highlight
-- bucket the user tagged at upload time. /me filters its grid by this
-- key when the user taps a highlight ring. Built-in keys: mountains,
-- beaches, foodie, suites, toppicks, solo. Custom keys are
-- "custom-<slug>" — generated by ProfilePhotoEditor.addCustomHighlight.
--
-- Applied live to project uxxhbdqedazpmvbvaosh via Supabase MCP at v112.1
-- ship time.

ALTER TABLE social_posts
  ADD COLUMN IF NOT EXISTS highlight_key TEXT;

CREATE INDEX IF NOT EXISTS idx_social_posts_highlight
  ON social_posts (author_id, highlight_key, created_at DESC)
  WHERE highlight_key IS NOT NULL;
