-- ═════════════════════════════════════════════════════════════════════════
-- LIVE-AI-03B — M7 STEP 1 — SUCCESSOR TRUSTED ACTIVATION BOUNDARY (V2) — Owner superuser migration
-- ⚠ UNAPPLIED / OFFLINE review artifact. NOT executed against any live database by this packet.
--   AI-STAGING Postgres b7362594-a01b-4623-a982-394707a6cec2 ONLY, under a SEPARATE explicit Owner authorization.
--   NEVER CORE-PROD (project 04c8b523-5b15-4d81-af06-8c2aa1a83499 / Postgres 1fbd7632-95ad-46f3-a20c-5be5b8e44e6b).
-- Generated by m7s1/build-sql.mjs from catalog/v2-digest-gen.mjs (T0=2026-09-28T15:26:23Z); do not hand-edit.
-- Adds a NEW schema live_ai_03b_trusted_v2 (owner live_ai_03b_fn_owner, PUBLIC revoked) holding
-- EXACTLY two SECURITY DEFINER functions (search_path = '' ; fully schema-qualified):
--   activate_catalog_v2(claims_json jsonb, p_execution_id text) RETURNS jsonb
--   restore_catalog_v2_inactive(claims_json jsonb, p_execution_id text) RETURNS jsonb
-- EXECUTE is granted ONLY to live_ai_03b_executor (+ USAGE on the new schema). Reader / gateway-store /
-- PUBLIC receive NOTHING. The functions consume the EXISTING accepted M6 single-use ledger
-- live_ai_03b_trusted.approval_consumption (owned by fn_owner; action CHECK unchanged) — NO ledger DDL.
-- WHY A NEW SCHEMA (minimum safe mechanism, proven by the local-PG suite): the frozen M6 canonical
-- post-verifier section E requires live_ai_03b_trusted to hold EXACTLY 1 relation + 2 functions, and the
-- frozen M6 functions are V1-literal-bound (expired). Adding functions there breaks the frozen verifier;
-- replacing them rewrites frozen M6 objects. A separate schema leaves every M6 object and verifier
-- section byte-exact. fn_owner already holds SELECT,UPDATE on the four lifecycle tables (M6) — NO new
-- grant to fn_owner. The executor keeps NO direct table/ledger privilege and NO CREATE anywhere.
-- Freshness uses PostgreSQL's own wall clock (clock_timestamp()) at the mutation boundary.
-- ═════════════════════════════════════════════════════════════════════════

\set ON_ERROR_STOP on
BEGIN;

-- ── precondition: the exact accepted M6 trusted boundary exists; successor schema absent ──
DO $pre$
DECLARE v_owner oid;
BEGIN
  SELECT oid INTO v_owner FROM pg_roles WHERE rolname='live_ai_03b_fn_owner' AND NOT rolcanlogin AND NOT rolsuper;
  IF v_owner IS NULL THEN RAISE EXCEPTION 'M7_TRUSTED_V2_PRECHECK: fn_owner absent or not the accepted NOLOGIN shape'; END IF;
  PERFORM 1 FROM pg_roles WHERE rolname='live_ai_03b_executor' AND rolcanlogin AND NOT rolsuper AND NOT rolcreatedb AND NOT rolcreaterole AND NOT rolbypassrls AND NOT rolreplication;
  IF NOT FOUND THEN RAISE EXCEPTION 'M7_TRUSTED_V2_PRECHECK: executor absent or not the accepted restricted shape'; END IF;
  PERFORM 1 FROM pg_namespace WHERE nspname='live_ai_03b_trusted' AND nspowner=v_owner;
  IF NOT FOUND THEN RAISE EXCEPTION 'M7_TRUSTED_V2_PRECHECK: accepted M6 trusted schema absent'; END IF;
  IF to_regclass('live_ai_03b_trusted.approval_consumption') IS NULL THEN RAISE EXCEPTION 'M7_TRUSTED_V2_PRECHECK: accepted M6 ledger absent'; END IF;
  IF (SELECT count(*) FROM pg_proc pr JOIN pg_namespace nn ON nn.oid=pr.pronamespace WHERE nn.nspname='live_ai_03b_trusted') <> 2 THEN
    RAISE EXCEPTION 'M7_TRUSTED_V2_PRECHECK: accepted M6 trusted schema does not hold exactly 2 functions'; END IF;
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname='live_ai_03b_trusted_v2') THEN
    RAISE EXCEPTION 'M7_TRUSTED_V2_PRECHECK: successor schema already exists (create-once)'; END IF;
  IF NOT (has_table_privilege('live_ai_03b_fn_owner','public.budget_price_catalog_versions','SELECT') AND has_table_privilege('live_ai_03b_fn_owner','public.budget_price_catalog_versions','UPDATE')
      AND has_table_privilege('live_ai_03b_fn_owner','public.budget_price_catalog_entries','SELECT') AND has_table_privilege('live_ai_03b_fn_owner','public.budget_price_catalog_entries','UPDATE')
      AND has_table_privilege('live_ai_03b_fn_owner','public.budget_policy_versions','SELECT') AND has_table_privilege('live_ai_03b_fn_owner','public.budget_control_epochs','SELECT')) THEN
    RAISE EXCEPTION 'M7_TRUSTED_V2_PRECHECK: fn_owner lacks the accepted M6 lifecycle-table privileges'; END IF;
END $pre$;

CREATE SCHEMA live_ai_03b_trusted_v2 AUTHORIZATION live_ai_03b_fn_owner;
REVOKE ALL ON SCHEMA live_ai_03b_trusted_v2 FROM PUBLIC;
GRANT USAGE ON SCHEMA live_ai_03b_trusted_v2 TO live_ai_03b_executor;

CREATE FUNCTION live_ai_03b_trusted_v2.activate_catalog_v2(claims_json jsonb, p_execution_id text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $fn$
DECLARE
  v_keys text[]; v_approval_id text; v_now timestamptz; v_consumed_at timestamptz; n bigint;
  v_content text := claims_json #>> '{content_digest}';
  v_nbf timestamptz; v_exp timestamptz; v_evv timestamptz; v_eve timestamptz;
  rts constant text := '^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$';
BEGIN
  IF claims_json IS NULL OR jsonb_typeof(claims_json) IS DISTINCT FROM 'object' THEN RAISE EXCEPTION 'activate_v2: claims must be a JSON object'; END IF;
  IF (claims_json #>> '{contract}') IS DISTINCT FROM 'VerifiedApprovalClaimsV2' THEN RAISE EXCEPTION 'activate_v2: claims contract mismatch (expected VerifiedApprovalClaimsV2)'; END IF;
  SELECT array_agg(k ORDER BY k COLLATE pg_catalog."C") INTO v_keys FROM jsonb_object_keys(claims_json) AS k;  -- byte order: deterministic under ANY database default collation
  IF v_keys IS DISTINCT FROM ARRAY['account_mode','activation_bundle_digest','active_catalog_digest','ai_staging_postgres','ai_staging_project','approval_expiry','approval_id','approval_not_before','base_commit','cache_write_rate_micros','catalog_verification_expiry','catalog_version_id','content_digest','context_tier','contract','core_excluded_postgres','core_excluded_project','currency','evidence_expiry','evidence_verified_at','execution_id','inactive_catalog_digest','input_rate_micros','model','one_call_money_ceiling_micros','one_call_policy_digest','one_call_policy_id','output_rate_micros','processing_mode','provider','receipt_id','regional_uplift','reviewer_fingerprint','service_tier','source_digest','unit_size']::text[] THEN RAISE EXCEPTION 'activate_v2: claims key set is not the exact VerifiedApprovalClaimsV2 shape'; END IF;
  v_approval_id := claims_json #>> '{approval_id}';
  IF v_approval_id IS NULL OR v_approval_id !~ '^[A-Za-z0-9._:-]{8,128}$' THEN RAISE EXCEPTION 'activate_v2: approval_id missing/malformed'; END IF;
  IF p_execution_id IS NULL OR p_execution_id !~ '^[A-Za-z0-9._:-]{8,128}$' OR (claims_json #>> '{execution_id}') IS DISTINCT FROM p_execution_id THEN
    RAISE EXCEPTION 'activate_v2: execution_id missing/malformed or not bound to verified claims';
  END IF;
  -- no arbitrary catalog / digest / policy: every identity is the exact reviewed literal.
  IF (claims_json #>> '{catalog_version_id}') IS DISTINCT FROM 'openai-gpt-5-6-terra-standard-short-v2' THEN RAISE EXCEPTION 'activate_v2: catalog_version_id is not the reviewed V2'; END IF;
  IF (claims_json #>> '{inactive_catalog_digest}') IS DISTINCT FROM '36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62' THEN RAISE EXCEPTION 'activate_v2: inactive_catalog_digest mismatch'; END IF;
  IF (claims_json #>> '{active_catalog_digest}') IS DISTINCT FROM '836548ef0274f3a068c83cf4d8e952eb6388921f2064c5e29e8ec25cd7eb798b' THEN RAISE EXCEPTION 'activate_v2: active_catalog_digest mismatch'; END IF;
  IF (claims_json #>> '{ai_staging_postgres}') IS DISTINCT FROM 'b7362594-a01b-4623-a982-394707a6cec2' OR (claims_json #>> '{ai_staging_project}') IS DISTINCT FROM '4ad1abb3-823a-4acf-b889-6d34ae46d7f9' THEN
    RAISE EXCEPTION 'activate_v2: target is not AI-STAGING'; END IF;
  IF (claims_json #>> '{core_excluded_postgres}') IS DISTINCT FROM '1fbd7632-95ad-46f3-a20c-5be5b8e44e6b' OR (claims_json #>> '{core_excluded_project}') IS DISTINCT FROM '04c8b523-5b15-4d81-af06-8c2aa1a83499' THEN
    RAISE EXCEPTION 'activate_v2: CORE-PROD exclusion binding mismatch'; END IF;
  IF v_content IS NULL OR v_content !~ '^[0-9a-f]{64}$' THEN RAISE EXCEPTION 'activate_v2: content_digest malformed'; END IF;
  IF (claims_json #>> '{source_digest}') IS DISTINCT FROM 'ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357' THEN RAISE EXCEPTION 'activate_v2: source_digest mismatch'; END IF;
  IF (claims_json #>> '{catalog_verification_expiry}') IS DISTINCT FROM '2026-10-05T15:26:23Z' THEN RAISE EXCEPTION 'activate_v2: catalog_verification_expiry does not match reviewed contract'; END IF;
  IF (claims_json #>> '{one_call_policy_id}') IS DISTINCT FROM 'live-ai-03b-policy-oneprobe-v2' OR (claims_json #>> '{one_call_policy_digest}') IS DISTINCT FROM '864e24817b2f98d741495bb403c20ada31cd4f27db3d9dfe1c50bb7d99ad9245' THEN
    RAISE EXCEPTION 'activate_v2: successor one-call policy binding mismatch'; END IF;
  IF (claims_json #> '{one_call_money_ceiling_micros}') IS DISTINCT FROM '105920'::jsonb THEN RAISE EXCEPTION 'activate_v2: one-call money ceiling is not 105920'; END IF;
  IF (claims_json #>> '{activation_bundle_digest}') IS DISTINCT FROM 'd6f40fc53dd6002fbed4990603aeddabe3bfff39b6a81aadc9e57dd6ef618e1e' THEN RAISE EXCEPTION 'activate_v2: activation_bundle_digest mismatch'; END IF;
  IF (claims_json #>> '{base_commit}') IS DISTINCT FROM '9270c282d5fd65e9fe49261391badfe92c777b8f' THEN RAISE EXCEPTION 'activate_v2: base_commit mismatch'; END IF;
  -- Standard / default service tier / direct / non-regional / short-context / USD / exact three rates.
  IF (claims_json #>> '{provider}') IS DISTINCT FROM 'openai' OR (claims_json #>> '{model}') IS DISTINCT FROM 'gpt-5.6-terra' THEN RAISE EXCEPTION 'activate_v2: provider/model mismatch'; END IF;
  IF (claims_json #>> '{account_mode}') IS DISTINCT FROM 'direct' THEN RAISE EXCEPTION 'activate_v2: account_mode is not direct'; END IF;
  IF (claims_json #>> '{processing_mode}') IS DISTINCT FROM 'standard' THEN RAISE EXCEPTION 'activate_v2: processing_mode is not standard'; END IF;
  IF (claims_json #>> '{service_tier}') IS DISTINCT FROM 'default' THEN RAISE EXCEPTION 'activate_v2: service_tier is not default'; END IF;
  IF (claims_json #>> '{context_tier}') IS DISTINCT FROM 'short' THEN RAISE EXCEPTION 'activate_v2: context_tier is not short'; END IF;
  IF (claims_json #> '{regional_uplift}') IS DISTINCT FROM 'false'::jsonb THEN RAISE EXCEPTION 'activate_v2: regional uplift present'; END IF;
  IF (claims_json #>> '{currency}') IS DISTINCT FROM 'USD' THEN RAISE EXCEPTION 'activate_v2: currency mismatch'; END IF;
  IF (claims_json #> '{input_rate_micros}') IS DISTINCT FROM '2000000'::jsonb
     OR (claims_json #> '{cache_write_rate_micros}') IS DISTINCT FROM '2500000'::jsonb
     OR (claims_json #> '{output_rate_micros}') IS DISTINCT FROM '12000000'::jsonb
     OR (claims_json #> '{unit_size}') IS DISTINCT FROM '1000000'::jsonb THEN
    RAISE EXCEPTION 'activate_v2: reviewed rate set mismatch (input/cache_write/output/unit)'; END IF;
  IF COALESCE(claims_json #>> '{approval_not_before}','') !~ rts OR COALESCE(claims_json #>> '{approval_expiry}','') !~ rts
     OR COALESCE(claims_json #>> '{evidence_verified_at}','') !~ rts OR COALESCE(claims_json #>> '{evidence_expiry}','') !~ rts THEN
    RAISE EXCEPTION 'activate_v2: approval/evidence validity timestamps missing or not strict RFC3339 UTC'; END IF;
  v_nbf := (claims_json #>> '{approval_not_before}')::timestamptz; v_exp := (claims_json #>> '{approval_expiry}')::timestamptz;
  v_evv := (claims_json #>> '{evidence_verified_at}')::timestamptz; v_eve := (claims_json #>> '{evidence_expiry}')::timestamptz;
  IF NOT (v_nbf < v_exp AND v_evv < v_eve) THEN RAISE EXCEPTION 'activate_v2: empty approval/evidence validity interval'; END IF;
  IF v_evv < TIMESTAMPTZ '2026-09-28T15:26:23Z' OR v_eve > TIMESTAMPTZ '2026-10-05T15:26:23Z' THEN RAISE EXCEPTION 'activate_v2: evidence window outside the V2 verification window'; END IF;

  -- SINGLE-USE: consume first (the accepted M6 ledger; 'activate' action). Replay / duplicate ⇒ fail closed.
  BEGIN
    INSERT INTO live_ai_03b_trusted.approval_consumption(approval_id, execution_id, content_digest, active_catalog_digest, action)
    VALUES (v_approval_id, p_execution_id, v_content, '836548ef0274f3a068c83cf4d8e952eb6388921f2064c5e29e8ec25cd7eb798b', 'activate')
    RETURNING consumed_at INTO v_consumed_at;
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION 'activate_v2: approval already consumed (replay rejected)';
  END;

  -- lock every catalog row for an atomic, race-free transition.
  PERFORM 1 FROM public.budget_price_catalog_versions FOR UPDATE;
  PERFORM 1 FROM public.budget_price_catalog_entries FOR UPDATE;

  -- exact predecessor: NOTHING active; exactly V1 (historical, inactive, byte-exact) + V2 (inactive, byte-exact).
  IF EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE status<>'inactive')
     OR EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE status<>'inactive') THEN
    RAISE EXCEPTION 'activate_v2: an active/revoked catalog version or entry already exists (no competing authority)'; END IF;
  IF (SELECT count(*) FROM public.budget_price_catalog_versions) <> 2 OR (SELECT count(*) FROM public.budget_price_catalog_entries) <> 5 THEN
    RAISE EXCEPTION 'activate_v2: unexpected catalog rows (expected exactly V1 + V2)'; END IF;
  IF NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v1' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND catalog_digest='453f928762b8e6cddedac8618786d008cb7a3d57ffefab9d0cfe3cda52c4c973' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v1') = 2
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_input_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_output_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) THEN RAISE EXCEPTION 'activate_v2: historical V1 not byte-exact'; END IF;
  IF NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v2' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND catalog_digest='36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')) OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v2') = 3
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier='cache_write'
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2500000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_output_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')) THEN
    RAISE EXCEPTION 'activate_v2: reviewed inactive V2 predecessor not matched'; END IF;
  -- gate order: catalog is armed FIRST — no active policy, controls still dormant.
  IF EXISTS (SELECT 1 FROM public.budget_policy_versions WHERE status='active') THEN RAISE EXCEPTION 'activate_v2: an active policy already exists (catalog must be armed first)'; END IF;
  IF NOT (EXISTS (SELECT 1 FROM public.budget_control_epochs WHERE scope_type='global' AND scope_key_digest='global'
       AND control_epoch=1 AND enabled=false AND killed=false AND record_digest='26136eb93212ccce1ba6f4b380dbb3f1f2ef64e3d16fa9754e287459cce525ee')
     AND EXISTS (SELECT 1 FROM public.budget_control_epochs WHERE scope_type='project' AND scope_key_digest='live-ai-03b'
       AND control_epoch=1 AND enabled=false AND killed=false AND record_digest='be70f6b477c7332a834720e4f784a7d724a6363d48cbcc590315ff2fc72cad7f')
     AND (SELECT count(*) FROM public.budget_control_epochs) = 2) THEN RAISE EXCEPTION 'activate_v2: controls are not exactly dormant'; END IF;

  -- DB-CLOCK freshness at the mutation boundary (real wall clock; never caller time / transaction start).
  v_now := clock_timestamp();
  IF v_now < TIMESTAMPTZ '2026-09-28T15:26:23Z' THEN RAISE EXCEPTION 'activate_v2: V2 verified_at is in the future at DB clock (%)', v_now; END IF;
  IF NOT (v_now < TIMESTAMPTZ '2026-10-05T15:26:23Z') THEN RAISE EXCEPTION 'activate_v2: V2 catalog verification expired at DB clock (%) — HOLD for a fresh successor', v_now; END IF;
  IF NOT (v_now >= v_nbf AND v_now < v_exp) THEN RAISE EXCEPTION 'activate_v2: DB clock outside signed approval validity interval'; END IF;
  IF NOT (v_now >= v_evv AND v_now < v_eve) THEN RAISE EXCEPTION 'activate_v2: DB clock outside signed evidence validity interval'; END IF;

  UPDATE public.budget_price_catalog_versions SET status='active', catalog_digest='836548ef0274f3a068c83cf4d8e952eb6388921f2064c5e29e8ec25cd7eb798b'
   WHERE id='openai-gpt-5-6-terra-standard-short-v2' AND status='inactive' AND catalog_digest='36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62';
  GET DIAGNOSTICS n = ROW_COUNT; IF n <> 1 THEN RAISE EXCEPTION 'activate_v2: version transition affected % rows', n; END IF;
  UPDATE public.budget_price_catalog_entries SET status='active'
   WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v2' AND status='inactive' AND id IN ('openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base', 'openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write', 'openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base');
  GET DIAGNOSTICS n = ROW_COUNT; IF n <> 3 THEN RAISE EXCEPTION 'activate_v2: entry transition affected % rows', n; END IF;

  -- postcondition: exactly ONE applicable authority (V2, exact active shape); V1 untouched.
  IF (SELECT count(*) FROM public.budget_price_catalog_versions WHERE status='active') <> 1 OR NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v2' AND status='active'
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND catalog_digest='836548ef0274f3a068c83cf4d8e952eb6388921f2064c5e29e8ec25cd7eb798b' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')) THEN
    RAISE EXCEPTION 'activate_v2: postcondition active version not exactly V2'; END IF;
  IF (SELECT count(*) FROM public.budget_price_catalog_entries WHERE status='active') <> 3 OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v2') = 3
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='active' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier='cache_write'
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2500000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='active' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_output_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='active' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')) THEN
    RAISE EXCEPTION 'activate_v2: postcondition active entries not exactly the three V2 entries'; END IF;
  IF NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v1' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND catalog_digest='453f928762b8e6cddedac8618786d008cb7a3d57ffefab9d0cfe3cda52c4c973' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v1') = 2
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_input_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_output_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) THEN RAISE EXCEPTION 'activate_v2: postcondition historical V1 changed'; END IF;

  RETURN jsonb_build_object(
    'contract', 'CatalogActivationReceiptV2', 'catalog_version_id', 'openai-gpt-5-6-terra-standard-short-v2',
    'approval_id', v_approval_id, 'execution_id', p_execution_id, 'content_digest', v_content,
    'active_catalog_digest', '836548ef0274f3a068c83cf4d8e952eb6388921f2064c5e29e8ec25cd7eb798b', 'action', 'activate',
    'consumed_at', to_char(v_consumed_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'));
END;
$fn$;
ALTER FUNCTION live_ai_03b_trusted_v2.activate_catalog_v2(jsonb, text) OWNER TO live_ai_03b_fn_owner;
REVOKE ALL ON FUNCTION live_ai_03b_trusted_v2.activate_catalog_v2(jsonb, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION live_ai_03b_trusted_v2.activate_catalog_v2(jsonb, text) TO live_ai_03b_executor;

CREATE FUNCTION live_ai_03b_trusted_v2.restore_catalog_v2_inactive(claims_json jsonb, p_execution_id text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = ''
AS $fn$
DECLARE
  v_keys text[]; v_approval_id text; n bigint; v_consumed_at timestamptz;
  is_active boolean; is_restored boolean;
BEGIN
  IF claims_json IS NULL OR jsonb_typeof(claims_json) IS DISTINCT FROM 'object' THEN RAISE EXCEPTION 'restore_v2: claims must be a JSON object'; END IF;
  IF (claims_json #>> '{contract}') IS DISTINCT FROM 'VerifiedApprovalClaimsV2' THEN RAISE EXCEPTION 'restore_v2: claims contract mismatch (expected VerifiedApprovalClaimsV2)'; END IF;
  SELECT array_agg(k ORDER BY k COLLATE pg_catalog."C") INTO v_keys FROM jsonb_object_keys(claims_json) AS k;  -- byte order: deterministic under ANY database default collation
  IF v_keys IS DISTINCT FROM ARRAY['account_mode','activation_bundle_digest','active_catalog_digest','ai_staging_postgres','ai_staging_project','approval_expiry','approval_id','approval_not_before','base_commit','cache_write_rate_micros','catalog_verification_expiry','catalog_version_id','content_digest','context_tier','contract','core_excluded_postgres','core_excluded_project','currency','evidence_expiry','evidence_verified_at','execution_id','inactive_catalog_digest','input_rate_micros','model','one_call_money_ceiling_micros','one_call_policy_digest','one_call_policy_id','output_rate_micros','processing_mode','provider','receipt_id','regional_uplift','reviewer_fingerprint','service_tier','source_digest','unit_size']::text[] THEN RAISE EXCEPTION 'restore_v2: claims key set is not the exact VerifiedApprovalClaimsV2 shape'; END IF;
  v_approval_id := claims_json #>> '{approval_id}';
  IF v_approval_id IS NULL OR v_approval_id !~ '^[A-Za-z0-9._:-]{8,128}$' THEN RAISE EXCEPTION 'restore_v2: approval_id missing/malformed'; END IF;
  IF p_execution_id IS NULL OR p_execution_id !~ '^[A-Za-z0-9._:-]{8,128}$' OR (claims_json #>> '{execution_id}') IS DISTINCT FROM p_execution_id THEN
    RAISE EXCEPTION 'restore_v2: execution_id missing/malformed or not bound to verified claims';
  END IF;
  -- no arbitrary catalog / digest / policy: every identity is the exact reviewed literal.
  IF (claims_json #>> '{catalog_version_id}') IS DISTINCT FROM 'openai-gpt-5-6-terra-standard-short-v2' THEN RAISE EXCEPTION 'restore_v2: catalog_version_id is not the reviewed V2'; END IF;
  IF (claims_json #>> '{inactive_catalog_digest}') IS DISTINCT FROM '36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62' THEN RAISE EXCEPTION 'restore_v2: inactive_catalog_digest mismatch'; END IF;
  IF (claims_json #>> '{active_catalog_digest}') IS DISTINCT FROM '836548ef0274f3a068c83cf4d8e952eb6388921f2064c5e29e8ec25cd7eb798b' THEN RAISE EXCEPTION 'restore_v2: active_catalog_digest mismatch'; END IF;
  IF (claims_json #>> '{ai_staging_postgres}') IS DISTINCT FROM 'b7362594-a01b-4623-a982-394707a6cec2' OR (claims_json #>> '{ai_staging_project}') IS DISTINCT FROM '4ad1abb3-823a-4acf-b889-6d34ae46d7f9' THEN
    RAISE EXCEPTION 'restore_v2: target is not AI-STAGING'; END IF;
  IF (claims_json #>> '{core_excluded_postgres}') IS DISTINCT FROM '1fbd7632-95ad-46f3-a20c-5be5b8e44e6b' OR (claims_json #>> '{core_excluded_project}') IS DISTINCT FROM '04c8b523-5b15-4d81-af06-8c2aa1a83499' THEN
    RAISE EXCEPTION 'restore_v2: CORE-PROD exclusion binding mismatch'; END IF;
  PERFORM 1 FROM public.budget_price_catalog_versions FOR UPDATE;
  PERFORM 1 FROM public.budget_price_catalog_entries FOR UPDATE;
  -- V1 must be historical + untouched in EVERY branch (restoration never revives V1).
  IF NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v1' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND catalog_digest='453f928762b8e6cddedac8618786d008cb7a3d57ffefab9d0cfe3cda52c4c973' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v1') = 2
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_input_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_output_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) THEN RAISE EXCEPTION 'restore_v2: historical V1 not byte-exact — HOLD'; END IF;
  is_active := (SELECT count(*) FROM public.budget_price_catalog_versions WHERE status<>'inactive') = 1
           AND (SELECT count(*) FROM public.budget_price_catalog_entries WHERE status<>'inactive') = 3
           AND EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v2' AND status='active'
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND catalog_digest='836548ef0274f3a068c83cf4d8e952eb6388921f2064c5e29e8ec25cd7eb798b' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z') AND (SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v2') = 3
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='active' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier='cache_write'
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2500000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='active' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_output_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='active' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z');
  is_restored := NOT EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE status<>'inactive')
           AND NOT EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE status<>'inactive')
           AND EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v2' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND catalog_digest='36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z') AND (SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v2') = 3
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier='cache_write'
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2500000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_output_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z');
  IF is_restored THEN
    -- idempotent: the exact reviewed inactive V2 state — no ledger write, no mutation.
    RETURN jsonb_build_object('contract', 'CatalogRestorationReceiptV2', 'catalog_version_id', 'openai-gpt-5-6-terra-standard-short-v2',
      'approval_id', v_approval_id, 'execution_id', p_execution_id, 'status', 'already_restored');
  END IF;
  IF NOT is_active THEN RAISE EXCEPTION 'restore_v2: neither the exact active V2 nor the exact restored state — ambiguous, HOLD'; END IF;
  BEGIN
    INSERT INTO live_ai_03b_trusted.approval_consumption(approval_id, execution_id, content_digest, active_catalog_digest, action)
    VALUES (v_approval_id || ':restore-v2', p_execution_id, '', '36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62', 'restore')
    RETURNING consumed_at INTO v_consumed_at;
  EXCEPTION WHEN unique_violation THEN
    RAISE EXCEPTION 'restore_v2: restoration approval already consumed (replay rejected)';
  END;
  UPDATE public.budget_price_catalog_versions SET status='inactive', catalog_digest='36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62'
   WHERE id='openai-gpt-5-6-terra-standard-short-v2' AND status='active' AND catalog_digest='836548ef0274f3a068c83cf4d8e952eb6388921f2064c5e29e8ec25cd7eb798b';
  GET DIAGNOSTICS n = ROW_COUNT; IF n <> 1 THEN RAISE EXCEPTION 'restore_v2: version transition affected % rows', n; END IF;
  UPDATE public.budget_price_catalog_entries SET status='inactive'
   WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v2' AND status='active' AND id IN ('openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base', 'openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write', 'openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base');
  GET DIAGNOSTICS n = ROW_COUNT; IF n <> 3 THEN RAISE EXCEPTION 'restore_v2: entry transition affected % rows', n; END IF;
  IF EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE status<>'inactive')
     OR EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE status<>'inactive')
     OR NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v2' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND catalog_digest='36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')) OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v2') = 3
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier='cache_write'
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2500000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_output_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z'))
     OR NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v1' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND catalog_digest='453f928762b8e6cddedac8618786d008cb7a3d57ffefab9d0cfe3cda52c4c973' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v1') = 2
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_input_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_output_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) THEN
    RAISE EXCEPTION 'restore_v2: postcondition is not the exact reviewed inactive state'; END IF;
  RETURN jsonb_build_object('contract', 'CatalogRestorationReceiptV2', 'catalog_version_id', 'openai-gpt-5-6-terra-standard-short-v2',
    'approval_id', v_approval_id, 'execution_id', p_execution_id, 'status', 'restored',
    'inactive_catalog_digest', '36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62',
    'consumed_at', to_char(v_consumed_at AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS"Z"'));
END;
$fn$;
ALTER FUNCTION live_ai_03b_trusted_v2.restore_catalog_v2_inactive(jsonb, text) OWNER TO live_ai_03b_fn_owner;
REVOKE ALL ON FUNCTION live_ai_03b_trusted_v2.restore_catalog_v2_inactive(jsonb, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION live_ai_03b_trusted_v2.restore_catalog_v2_inactive(jsonb, text) TO live_ai_03b_executor;

-- ── postcondition: exact successor ACL shape; M6 objects untouched ──
DO $post$
DECLARE v_owner oid := (SELECT oid FROM pg_roles WHERE rolname='live_ai_03b_fn_owner'); v_exec oid := (SELECT oid FROM pg_roles WHERE rolname='live_ai_03b_executor');
BEGIN
  IF (SELECT count(*) FROM pg_proc pr JOIN pg_namespace nn ON nn.oid=pr.pronamespace WHERE nn.nspname='live_ai_03b_trusted_v2') <> 2
     OR (SELECT count(*) FROM pg_class c JOIN pg_namespace nn ON nn.oid=c.relnamespace WHERE nn.nspname='live_ai_03b_trusted_v2') <> 0 THEN
    RAISE EXCEPTION 'M7_TRUSTED_V2_POSTCHECK: successor schema must hold exactly 2 functions and no relation'; END IF;
  IF EXISTS (SELECT 1 FROM pg_proc pr JOIN pg_namespace nn ON nn.oid=pr.pronamespace WHERE nn.nspname='live_ai_03b_trusted_v2'
             AND NOT (pr.prosecdef AND pr.proowner=v_owner AND pr.proconfig = ARRAY['search_path=""'])) THEN
    RAISE EXCEPTION 'M7_TRUSTED_V2_POSTCHECK: a successor function is not SECURITY DEFINER / fn_owner / empty search_path'; END IF;
  IF EXISTS (SELECT 1 FROM pg_proc pr JOIN pg_namespace nn ON nn.oid=pr.pronamespace CROSS JOIN LATERAL aclexplode(pr.proacl) a
             WHERE nn.nspname='live_ai_03b_trusted_v2' AND a.grantee NOT IN (v_owner, v_exec)) THEN
    RAISE EXCEPTION 'M7_TRUSTED_V2_POSTCHECK: a successor function is executable by a principal other than fn_owner/executor'; END IF;
  IF EXISTS (SELECT 1 FROM pg_namespace nn CROSS JOIN LATERAL aclexplode(nn.nspacl) a WHERE nn.nspname='live_ai_03b_trusted_v2'
             AND NOT (a.grantee=v_owner OR (a.grantee=v_exec AND a.privilege_type='USAGE'))) THEN
    RAISE EXCEPTION 'M7_TRUSTED_V2_POSTCHECK: successor schema ACL is not exactly {fn_owner, executor USAGE}'; END IF;
  IF (SELECT count(*) FROM pg_proc pr JOIN pg_namespace nn ON nn.oid=pr.pronamespace WHERE nn.nspname='live_ai_03b_trusted') <> 2 THEN
    RAISE EXCEPTION 'M7_TRUSTED_V2_POSTCHECK: M6 trusted schema changed'; END IF;
  RAISE NOTICE 'M7 trusted successor OK — live_ai_03b_trusted_v2 (2 SECURITY DEFINER functions, executor-only EXECUTE)';
END $post$;

COMMIT;
