-- ═════════════════════════════════════════════════════════════════════════
-- LIVE-AI-03B — M7 STEP 1 — V2 CATALOG ACTIVATION — trusted executor invocation contract
-- ⚠ UNAPPLIED / OFFLINE review artifact. NOT executed against any live database by this packet.
--   AI-STAGING Postgres b7362594-a01b-4623-a982-394707a6cec2 ONLY, under a SEPARATE explicit Owner authorization.
--   NEVER CORE-PROD (project 04c8b523-5b15-4d81-af06-8c2aa1a83499 / Postgres 1fbd7632-95ad-46f3-a20c-5be5b8e44e6b).
-- Generated by m7s1/build-sql.mjs from catalog/v2-digest-gen.mjs (T0=2026-09-28T15:26:23Z); do not hand-edit.
-- The ONLY authorized path: the restricted executor role invokes
--   live_ai_03b_trusted_v2.activate_catalog_v2(verified_claims_json, execution_id)
-- with the VerifiedApprovalClaimsV2 object emitted by approval/approval-verify-v2.mjs AFTER successful
-- Ed25519 verification against the independently pinned reviewer trust root. This file performs NO raw
-- catalog UPDATE and confers NO operator authority. Fails closed unless run as live_ai_03b_executor.
-- REQUIRED: -v verified_claims_json='<VerifiedApprovalClaimsV2>'  -v execution_id='<approval-bound nonce>'
-- ═════════════════════════════════════════════════════════════════════════

\set ON_ERROR_STOP on
\if :{?verified_claims_json}
\else
\echo 'FATAL: verified_claims_json not supplied (fail closed).'
\quit
\endif
\if :{?execution_id}
\else
\echo 'FATAL: execution_id not supplied (fail closed).'
\quit
\endif
BEGIN;
DO $$
BEGIN
  IF current_user <> 'live_ai_03b_executor' THEN
    RAISE EXCEPTION 'v2-activate: not the restricted trusted executor role (current_user=%)', current_user;
  END IF;
END $$;
SELECT live_ai_03b_trusted_v2.activate_catalog_v2(:'verified_claims_json'::jsonb, :'execution_id');
COMMIT;
