-- ═════════════════════════════════════════════════════════════════════════
-- LIVE-AI-03B — M7 STEP 1 — SUCCESSOR POST-APPLY VERIFIER (READ ONLY; UNAPPLIED)
-- ⚠ UNAPPLIED / OFFLINE review artifact. NOT executed against any live database by this packet.
--   AI-STAGING Postgres b7362594-a01b-4623-a982-394707a6cec2 ONLY, under a SEPARATE explicit Owner authorization.
--   NEVER CORE-PROD (project 04c8b523-5b15-4d81-af06-8c2aa1a83499 / Postgres 1fbd7632-95ad-46f3-a20c-5be5b8e44e6b).
-- Generated by m7s1/build-sql.mjs from catalog/v2-digest-gen.mjs (T0=2026-09-28T15:26:23Z); do not hand-edit.
-- Proves, after the Owner applies 01 (V2 inactive seed) + 02 (trusted successor):
--   A. successor schema/functions/ACL exact (fn_owner; SECURITY DEFINER; search_path=""; EXECUTE only
--      fn_owner+executor; schema USAGE only executor; no PUBLIC; no relation in the schema);
--   B. executor has NO privilege on any BUDGET table / the ledger and NO CREATE anywhere relevant;
--   C. reader + gateway-store hold NO USAGE / EXECUTE on the successor (no activation authority);
--   D. V2 exact INACTIVE (3 entries) + V1 historical byte-exact + nothing active + policy/controls dormant;
--   E. the accepted M6 boundary is unchanged (the frozen M6 canonical post-verifier must ALSO pass).
-- Performs NO mutation (BEGIN READ ONLY … ROLLBACK).
-- ═════════════════════════════════════════════════════════════════════════

\set ON_ERROR_STOP on
SET statement_timeout = '15s';
SET default_transaction_read_only = on;
BEGIN READ ONLY;
DO $verify$
DECLARE
  v_owner oid := (SELECT oid FROM pg_roles WHERE rolname='live_ai_03b_fn_owner');
  v_exec oid := (SELECT oid FROM pg_roles WHERE rolname='live_ai_03b_executor');
  budget_tables text[] := ARRAY['budget_control_epochs','budget_decisions','budget_envelope_allocations','budget_envelopes','budget_execution_consumptions','budget_policy_versions','budget_price_catalog_entries','budget_price_catalog_versions','budget_provider_reservations','budget_provider_settlements','budget_reconciliations','budget_scope_counters','budget_sessions'];
  privs text[] := ARRAY['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'];
  fns text[] := ARRAY['live_ai_03b_trusted_v2.activate_catalog_v2(jsonb,text)','live_ai_03b_trusted_v2.restore_catalog_v2_inactive(jsonb,text)'];
  t text; p text; r text; f text;
BEGIN
  IF v_owner IS NULL OR v_exec IS NULL THEN RAISE EXCEPTION 'v2-verify: fn_owner/executor absent'; END IF;
  -- A
  PERFORM 1 FROM pg_namespace WHERE nspname='live_ai_03b_trusted_v2' AND nspowner=v_owner;
  IF NOT FOUND THEN RAISE EXCEPTION 'v2-verify: successor schema missing or not owned by fn_owner'; END IF;
  IF (SELECT count(*) FROM pg_proc pr JOIN pg_namespace nn ON nn.oid=pr.pronamespace WHERE nn.nspname='live_ai_03b_trusted_v2') <> 2 THEN RAISE EXCEPTION 'v2-verify: successor schema must hold exactly 2 functions'; END IF;
  IF (SELECT count(*) FROM pg_class c JOIN pg_namespace nn ON nn.oid=c.relnamespace WHERE nn.nspname='live_ai_03b_trusted_v2') <> 0 THEN RAISE EXCEPTION 'v2-verify: successor schema holds a relation'; END IF;
  FOREACH f IN ARRAY fns LOOP
    PERFORM 1 FROM pg_proc WHERE oid=f::regprocedure AND prosecdef AND proowner=v_owner AND proconfig = ARRAY['search_path=""'] AND prolang=(SELECT oid FROM pg_language WHERE lanname='plpgsql');
    IF NOT FOUND THEN RAISE EXCEPTION 'v2-verify: % not SECURITY DEFINER / fn_owner / exact empty search_path', f; END IF;
    IF EXISTS (SELECT 1 FROM aclexplode((SELECT proacl FROM pg_proc WHERE oid=f::regprocedure)) a WHERE a.grantee NOT IN (v_owner, v_exec)) THEN RAISE EXCEPTION 'v2-verify: % executable by an unexpected principal (incl. PUBLIC)', f; END IF;
    IF (SELECT proacl FROM pg_proc WHERE oid=f::regprocedure) IS NULL THEN RAISE EXCEPTION 'v2-verify: % has default ACL (PUBLIC EXECUTE)', f; END IF;
    IF NOT has_function_privilege('live_ai_03b_executor', f, 'EXECUTE') THEN RAISE EXCEPTION 'v2-verify: executor lacks EXECUTE on %', f; END IF;
  END LOOP;
  IF EXISTS (SELECT 1 FROM pg_namespace nn CROSS JOIN LATERAL aclexplode(nn.nspacl) a WHERE nn.nspname='live_ai_03b_trusted_v2'
             AND NOT (a.grantee=v_owner OR (a.grantee=v_exec AND a.privilege_type='USAGE'))) THEN RAISE EXCEPTION 'v2-verify: successor schema ACL not exactly {fn_owner, executor USAGE}'; END IF;
  -- B
  FOREACH t IN ARRAY budget_tables LOOP FOREACH p IN ARRAY privs LOOP
    IF has_table_privilege('live_ai_03b_executor','public.'||t,p) THEN RAISE EXCEPTION 'v2-verify: executor holds % on public.%', p, t; END IF;
  END LOOP; END LOOP;
  FOREACH p IN ARRAY privs LOOP IF has_table_privilege('live_ai_03b_executor','live_ai_03b_trusted.approval_consumption',p) THEN RAISE EXCEPTION 'v2-verify: executor holds % on the ledger', p; END IF; END LOOP;
  IF has_schema_privilege('live_ai_03b_executor','live_ai_03b_trusted_v2','CREATE') OR has_schema_privilege('live_ai_03b_executor','live_ai_03b_trusted','CREATE')
     OR has_schema_privilege('live_ai_03b_executor','public','CREATE') THEN RAISE EXCEPTION 'v2-verify: executor holds schema CREATE'; END IF;
  -- C
  FOREACH r IN ARRAY ARRAY['live_ai_03b_reader','live_ai_03b_gateway_store'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname=r) THEN
      IF has_schema_privilege(r,'live_ai_03b_trusted_v2','USAGE') OR has_schema_privilege(r,'live_ai_03b_trusted_v2','CREATE') THEN RAISE EXCEPTION 'v2-verify: % holds successor-schema privilege', r; END IF;
      FOREACH f IN ARRAY fns LOOP IF has_function_privilege(r, f, 'EXECUTE') THEN RAISE EXCEPTION 'v2-verify: % holds EXECUTE on %', r, f; END IF; END LOOP;
      FOREACH t IN ARRAY ARRAY['budget_price_catalog_versions','budget_price_catalog_entries'] LOOP
        FOREACH p IN ARRAY ARRAY['INSERT','UPDATE','DELETE','TRUNCATE'] LOOP
          IF has_table_privilege(r,'public.'||t,p) THEN RAISE EXCEPTION 'v2-verify: % holds % on public.% (catalog write = activation authority)', r, p, t; END IF;
        END LOOP;
      END LOOP;
    ELSE RAISE EXCEPTION 'v2-verify: expected role % absent', r; END IF;
  END LOOP;
  -- D
  IF NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v1' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND catalog_digest='453f928762b8e6cddedac8618786d008cb7a3d57ffefab9d0cfe3cda52c4c973' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v1') = 2
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_input_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_output_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) THEN RAISE EXCEPTION 'v2-verify: historical V1 not byte-exact inactive'; END IF;
  IF NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v2' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND catalog_digest='36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')) OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v2') = 3
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier='cache_write'
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2500000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_output_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')) THEN RAISE EXCEPTION 'v2-verify: V2 not exactly the reviewed inactive seed'; END IF;
  IF (SELECT count(*) FROM public.budget_price_catalog_versions) <> 2 OR (SELECT count(*) FROM public.budget_price_catalog_entries) <> 5 THEN RAISE EXCEPTION 'v2-verify: unexpected catalog rows'; END IF;
  IF EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE status<>'inactive') OR EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE status<>'inactive') THEN RAISE EXCEPTION 'v2-verify: an active/revoked catalog exists'; END IF;
  IF (SELECT count(*) FROM public.budget_policy_versions) <> 1 OR NOT (EXISTS (SELECT 1 FROM public.budget_policy_versions WHERE id='live-ai-03b-policy-v1-dormant' AND project_id='live-ai-03b' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-18T14:11:25Z' AND effective_until IS NULL
       AND session_money_ceiling_micros=0 AND session_provider_calls=0 AND session_execution_admissions=0
       AND subject_day_money_ceiling_micros=0 AND project_day_money_ceiling_micros=0
       AND project_month_money_ceiling_micros=0 AND global_day_money_ceiling_micros=0
       AND policy_digest='cf5ae64ff17eca76ac3f19c4dd2b5157a1b9bb601f765978e24eb47bbc2308c4' AND created_at=TIMESTAMPTZ '2026-09-18T14:11:25Z')) THEN RAISE EXCEPTION 'v2-verify: policy not exactly dormant'; END IF;
  IF NOT (EXISTS (SELECT 1 FROM public.budget_control_epochs WHERE scope_type='global' AND scope_key_digest='global'
       AND control_epoch=1 AND enabled=false AND killed=false AND record_digest='26136eb93212ccce1ba6f4b380dbb3f1f2ef64e3d16fa9754e287459cce525ee')
     AND EXISTS (SELECT 1 FROM public.budget_control_epochs WHERE scope_type='project' AND scope_key_digest='live-ai-03b'
       AND control_epoch=1 AND enabled=false AND killed=false AND record_digest='be70f6b477c7332a834720e4f784a7d724a6363d48cbcc590315ff2fc72cad7f')
     AND (SELECT count(*) FROM public.budget_control_epochs) = 2) THEN RAISE EXCEPTION 'v2-verify: controls not exactly dormant'; END IF;
  IF EXISTS (SELECT 1 FROM live_ai_03b_trusted.approval_consumption WHERE active_catalog_digest IN ('836548ef0274f3a068c83cf4d8e952eb6388921f2064c5e29e8ec25cd7eb798b', '36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62')) THEN RAISE EXCEPTION 'v2-verify: a V2 approval was already consumed (not the fresh pre-activation state)'; END IF;
  RAISE NOTICE 'M7 V2 POST-APPLY VERIFICATION: ALL HARD CHECKS PASSED (run the frozen M6 canonical post-verifier as well)';
END $verify$;
ROLLBACK;
