-- ═════════════════════════════════════════════════════════════════════════
-- LIVE-AI-03B — M7 STEP 1 — SUCCESSOR V2 INACTIVE PRICE-CATALOG SEED (Owner-applied)
-- ⚠ UNAPPLIED / OFFLINE review artifact. NOT executed against any live database by this packet.
--   AI-STAGING Postgres b7362594-a01b-4623-a982-394707a6cec2 ONLY, under a SEPARATE explicit Owner authorization.
--   NEVER CORE-PROD (project 04c8b523-5b15-4d81-af06-8c2aa1a83499 / Postgres 1fbd7632-95ad-46f3-a20c-5be5b8e44e6b).
-- Generated by m7s1/build-sql.mjs from catalog/v2-digest-gen.mjs (T0=2026-09-28T15:26:23Z); do not hand-edit.
-- Inserts EXACTLY one INACTIVE successor catalog version + THREE INACTIVE entries:
--   version openai-gpt-5-6-terra-standard-short-v2
--   openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base   input  tier NULL        rate 2000000 / 1000000
--   openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write   input  tier cache_write rate 2500000 / 1000000
--   openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base   output tier NULL        rate 12000000 / 1000000
-- V1 (openai-gpt-5-6-terra-standard-short-v1) is PRESERVED BYTE-EXACT (never extended / refreshed / rewritten /
-- reactivated). Frozen literals only (no now()/CURRENT_TIMESTAMP/clock_timestamp()):
--   T0 = 2026-09-28T15:26:23Z   verification_expires_at = 2026-10-05T15:26:23Z (T0 + 7 calendar days)
--   source_digest = ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357
--   inactive catalog_digest = 36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62
-- Precondition = the exact accepted post-M6 BUDGET state (13 tables; 2 dormant controls;
-- 1 dormant policy; V1 = 1 inactive version + 2 inactive entries; 9 accounting tables empty;
-- nothing active; V2 absent). Postcondition = exact 6 → 10 rows. Any mismatch RAISEs → ROLLBACK.
-- ═════════════════════════════════════════════════════════════════════════

\set ON_ERROR_STOP on
BEGIN;

LOCK TABLE
  public.budget_control_epochs,
  public.budget_decisions,
  public.budget_envelope_allocations,
  public.budget_envelopes,
  public.budget_execution_consumptions,
  public.budget_policy_versions,
  public.budget_price_catalog_entries,
  public.budget_price_catalog_versions,
  public.budget_provider_reservations,
  public.budget_provider_settlements,
  public.budget_reconciliations,
  public.budget_scope_counters,
  public.budget_sessions
IN SHARE ROW EXCLUSIVE MODE;

DO $precheck$
DECLARE
  expected text[] := ARRAY['budget_control_epochs','budget_decisions','budget_envelope_allocations','budget_envelopes','budget_execution_consumptions','budget_policy_versions','budget_price_catalog_entries','budget_price_catalog_versions','budget_provider_reservations','budget_provider_settlements','budget_reconciliations','budget_scope_counters','budget_sessions'];
  zero_tables text[] := ARRAY['budget_decisions','budget_envelope_allocations','budget_envelopes','budget_execution_consumptions','budget_provider_reservations','budget_provider_settlements','budget_reconciliations','budget_scope_counters','budget_sessions'];
  t text; n bigint; unexpected text; total_budget int;
BEGIN
  FOREACH t IN ARRAY expected LOOP
    IF to_regclass('public.' || t) IS NULL THEN RAISE EXCEPTION 'M7_V2_SEED_PRECHECK: missing budget table %', t; END IF;
  END LOOP;
  SELECT string_agg(table_name, ',') INTO unexpected FROM information_schema.tables
   WHERE table_schema='public' AND table_type='BASE TABLE' AND table_name LIKE 'budget\_%' ESCAPE '\' AND NOT (table_name = ANY(expected));
  IF unexpected IS NOT NULL THEN RAISE EXCEPTION 'M7_V2_SEED_PRECHECK: unexpected budget table(s): %', unexpected; END IF;
  SELECT count(*) INTO total_budget FROM information_schema.tables
   WHERE table_schema='public' AND table_type='BASE TABLE' AND table_name LIKE 'budget\_%' ESCAPE '\';
  IF total_budget <> 13 THEN RAISE EXCEPTION 'M7_V2_SEED_PRECHECK: expected 13 budget tables, found %', total_budget; END IF;

  IF NOT (EXISTS (SELECT 1 FROM public.budget_control_epochs WHERE scope_type='global' AND scope_key_digest='global'
       AND control_epoch=1 AND enabled=false AND killed=false AND record_digest='26136eb93212ccce1ba6f4b380dbb3f1f2ef64e3d16fa9754e287459cce525ee')
     AND EXISTS (SELECT 1 FROM public.budget_control_epochs WHERE scope_type='project' AND scope_key_digest='live-ai-03b'
       AND control_epoch=1 AND enabled=false AND killed=false AND record_digest='be70f6b477c7332a834720e4f784a7d724a6363d48cbcc590315ff2fc72cad7f')
     AND (SELECT count(*) FROM public.budget_control_epochs) = 2) THEN RAISE EXCEPTION 'M7_V2_SEED_PRECHECK: dormant control rows not exactly matched'; END IF;
  IF (SELECT count(*) FROM public.budget_policy_versions) <> 1 OR NOT (EXISTS (SELECT 1 FROM public.budget_policy_versions WHERE id='live-ai-03b-policy-v1-dormant' AND project_id='live-ai-03b' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-18T14:11:25Z' AND effective_until IS NULL
       AND session_money_ceiling_micros=0 AND session_provider_calls=0 AND session_execution_admissions=0
       AND subject_day_money_ceiling_micros=0 AND project_day_money_ceiling_micros=0
       AND project_month_money_ceiling_micros=0 AND global_day_money_ceiling_micros=0
       AND policy_digest='cf5ae64ff17eca76ac3f19c4dd2b5157a1b9bb601f765978e24eb47bbc2308c4' AND created_at=TIMESTAMPTZ '2026-09-18T14:11:25Z')) THEN
    RAISE EXCEPTION 'M7_V2_SEED_PRECHECK: policy state is not exactly the single dormant policy (an old one-call policy must NOT be present)';
  END IF;
  IF (SELECT count(*) FROM public.budget_price_catalog_versions) <> 1 OR NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v1' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND catalog_digest='453f928762b8e6cddedac8618786d008cb7a3d57ffefab9d0cfe3cda52c4c973' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) THEN
    RAISE EXCEPTION 'M7_V2_SEED_PRECHECK: catalog versions are not exactly the historical inactive V1';
  END IF;
  IF (SELECT count(*) FROM public.budget_price_catalog_entries) <> 2 OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v1') = 2
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_input_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_output_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) THEN
    RAISE EXCEPTION 'M7_V2_SEED_PRECHECK: catalog entries are not exactly the historical inactive V1 pair';
  END IF;
  FOREACH t IN ARRAY zero_tables LOOP
    EXECUTE format('SELECT count(*) FROM public.%I', t) INTO n;
    IF n <> 0 THEN RAISE EXCEPTION 'M7_V2_SEED_PRECHECK: table % must be empty, found %', t, n; END IF;
  END LOOP;
  IF EXISTS (SELECT 1 FROM public.budget_control_epochs WHERE enabled OR killed)
     OR EXISTS (SELECT 1 FROM public.budget_policy_versions WHERE status='active')
     OR EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE status<>'inactive')
     OR EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE status<>'inactive') THEN
    RAISE EXCEPTION 'M7_V2_SEED_PRECHECK: nothing may be active/enabled/killed/revoked';
  END IF;
  IF EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v2')
     OR EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v2') THEN
    RAISE EXCEPTION 'M7_V2_SEED_PRECHECK: V2 already present (create-once)';
  END IF;
END
$precheck$;

INSERT INTO public.budget_price_catalog_versions (id, status, effective_from, effective_until, catalog_digest, created_at)
VALUES ('openai-gpt-5-6-terra-standard-short-v2', 'inactive', TIMESTAMPTZ '2026-09-28T15:26:23Z', NULL, '36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62', TIMESTAMPTZ '2026-09-28T15:26:23Z');

INSERT INTO public.budget_price_catalog_entries
  (id, catalog_version_id, provider, model, service_tier, billing_dimension, currency_code, unit_size, rate_micros,
   effective_from, effective_until, verified_at, verification_expires_at, source_id, source_digest, status, created_at)
VALUES
  ('openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base', 'openai-gpt-5-6-terra-standard-short-v2', 'openai', 'gpt-5.6-terra', NULL, 'reasoning_input_token', 'USD', 1000000, 2000000,
   TIMESTAMPTZ '2026-09-28T15:26:23Z', NULL, TIMESTAMPTZ '2026-09-28T15:26:23Z', TIMESTAMPTZ '2026-10-05T15:26:23Z', 'openai-api-pricing/gpt-5.6-terra/standard/short-context/v1', 'ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357', 'inactive', TIMESTAMPTZ '2026-09-28T15:26:23Z'),
  ('openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write', 'openai-gpt-5-6-terra-standard-short-v2', 'openai', 'gpt-5.6-terra', 'cache_write', 'reasoning_input_token', 'USD', 1000000, 2500000,
   TIMESTAMPTZ '2026-09-28T15:26:23Z', NULL, TIMESTAMPTZ '2026-09-28T15:26:23Z', TIMESTAMPTZ '2026-10-05T15:26:23Z', 'openai-api-pricing/gpt-5.6-terra/standard/short-context/v1', 'ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357', 'inactive', TIMESTAMPTZ '2026-09-28T15:26:23Z'),
  ('openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base', 'openai-gpt-5-6-terra-standard-short-v2', 'openai', 'gpt-5.6-terra', NULL, 'reasoning_output_token', 'USD', 1000000, 12000000,
   TIMESTAMPTZ '2026-09-28T15:26:23Z', NULL, TIMESTAMPTZ '2026-09-28T15:26:23Z', TIMESTAMPTZ '2026-10-05T15:26:23Z', 'openai-api-pricing/gpt-5.6-terra/standard/short-context/v1', 'ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357', 'inactive', TIMESTAMPTZ '2026-09-28T15:26:23Z');

DO $postcheck$
DECLARE zero_tables text[] := ARRAY['budget_decisions','budget_envelope_allocations','budget_envelopes','budget_execution_consumptions','budget_provider_reservations','budget_provider_settlements','budget_reconciliations','budget_scope_counters','budget_sessions']; t text; n bigint; total bigint;
BEGIN
  IF NOT (EXISTS (SELECT 1 FROM public.budget_control_epochs WHERE scope_type='global' AND scope_key_digest='global'
       AND control_epoch=1 AND enabled=false AND killed=false AND record_digest='26136eb93212ccce1ba6f4b380dbb3f1f2ef64e3d16fa9754e287459cce525ee')
     AND EXISTS (SELECT 1 FROM public.budget_control_epochs WHERE scope_type='project' AND scope_key_digest='live-ai-03b'
       AND control_epoch=1 AND enabled=false AND killed=false AND record_digest='be70f6b477c7332a834720e4f784a7d724a6363d48cbcc590315ff2fc72cad7f')
     AND (SELECT count(*) FROM public.budget_control_epochs) = 2) THEN RAISE EXCEPTION 'M7_V2_SEED_POSTCHECK: dormant controls changed'; END IF;
  IF (SELECT count(*) FROM public.budget_policy_versions) <> 1 OR NOT (EXISTS (SELECT 1 FROM public.budget_policy_versions WHERE id='live-ai-03b-policy-v1-dormant' AND project_id='live-ai-03b' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-18T14:11:25Z' AND effective_until IS NULL
       AND session_money_ceiling_micros=0 AND session_provider_calls=0 AND session_execution_admissions=0
       AND subject_day_money_ceiling_micros=0 AND project_day_money_ceiling_micros=0
       AND project_month_money_ceiling_micros=0 AND global_day_money_ceiling_micros=0
       AND policy_digest='cf5ae64ff17eca76ac3f19c4dd2b5157a1b9bb601f765978e24eb47bbc2308c4' AND created_at=TIMESTAMPTZ '2026-09-18T14:11:25Z')) THEN RAISE EXCEPTION 'M7_V2_SEED_POSTCHECK: dormant policy changed'; END IF;
  IF NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v1' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND catalog_digest='453f928762b8e6cddedac8618786d008cb7a3d57ffefab9d0cfe3cda52c4c973' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v1') = 2
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_input_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v1-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v1'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL AND billing_dimension='reasoning_output_token'
       AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-18T18:37:35Z' AND verification_expires_at=TIMESTAMPTZ '2026-09-25T18:37:35Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='fda6f4a834b2277bd0ace30738cda1e8f75c0f8bc523ddbd11c966c4da52beb3'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-18T18:37:35Z')) THEN RAISE EXCEPTION 'M7_V2_SEED_POSTCHECK: historical V1 changed'; END IF;
  IF (SELECT count(*) FROM public.budget_price_catalog_versions) <> 2 OR NOT (EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE id='openai-gpt-5-6-terra-standard-short-v2' AND status='inactive'
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND catalog_digest='36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')) THEN
    RAISE EXCEPTION 'M7_V2_SEED_POSTCHECK: V2 version row not exact'; END IF;
  IF (SELECT count(*) FROM public.budget_price_catalog_entries) <> 5 OR NOT ((SELECT count(*) FROM public.budget_price_catalog_entries WHERE catalog_version_id='openai-gpt-5-6-terra-standard-short-v2') = 3
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-input-token-cache-write' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier='cache_write'
       AND billing_dimension='reasoning_input_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=2500000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')
     AND EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE id='openai-gpt-5-6-terra-standard-short-v2-reasoning-output-token-base' AND catalog_version_id='openai-gpt-5-6-terra-standard-short-v2'
       AND provider='openai' AND model='gpt-5.6-terra' AND service_tier IS NULL
       AND billing_dimension='reasoning_output_token' AND currency_code='USD' AND unit_size=1000000 AND rate_micros=12000000
       AND effective_from=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND effective_until IS NULL
       AND verified_at=TIMESTAMPTZ '2026-09-28T15:26:23Z' AND verification_expires_at=TIMESTAMPTZ '2026-10-05T15:26:23Z'
       AND source_id='openai-api-pricing/gpt-5.6-terra/standard/short-context/v1' AND source_digest='ec23657bf0c20390afec4d4f233f14300e43b136cc6f27c25d6ffc35e1d7b357'
       AND status='inactive' AND created_at=TIMESTAMPTZ '2026-09-28T15:26:23Z')) THEN
    RAISE EXCEPTION 'M7_V2_SEED_POSTCHECK: V2 entry rows not exact'; END IF;
  IF EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE status<>'inactive')
     OR EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE status<>'inactive') THEN
    RAISE EXCEPTION 'M7_V2_SEED_POSTCHECK: no active/revoked catalog allowed'; END IF;
  IF EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE '*' IN (provider, model, billing_dimension, currency_code) OR service_tier='*'
               OR provider<>'openai' OR model<>'gpt-5.6-terra' OR currency_code<>'USD'
               OR billing_dimension NOT IN ('reasoning_input_token','reasoning_output_token')
               OR COALESCE(service_tier,'<null>') NOT IN ('<null>','cache_write')) THEN
    RAISE EXCEPTION 'M7_V2_SEED_POSTCHECK: wildcard / alternate provider|model|currency|dimension|tier present'; END IF;
  total := (SELECT count(*) FROM public.budget_control_epochs) + (SELECT count(*) FROM public.budget_policy_versions)
         + (SELECT count(*) FROM public.budget_price_catalog_versions) + (SELECT count(*) FROM public.budget_price_catalog_entries);
  FOREACH t IN ARRAY zero_tables LOOP
    EXECUTE format('SELECT count(*) FROM public.%I', t) INTO n;
    IF n <> 0 THEN RAISE EXCEPTION 'M7_V2_SEED_POSTCHECK: table % must remain empty', t; END IF;
    total := total + n;
  END LOOP;
  IF total <> 10 THEN RAISE EXCEPTION 'M7_V2_SEED_POSTCHECK: expected exactly 10 budget rows, found %', total; END IF;
  RAISE NOTICE 'M7 V2 inactive seed OK — V2 inactive (3 entries); V1 historical preserved; nothing active';
END
$postcheck$;

COMMIT;
