-- ═════════════════════════════════════════════════════════════════════════
-- LIVE-AI-03B — M7 STEP 1 — SUCCESSOR TRUSTED-BOUNDARY ROLLBACK (Owner; PRE-ACTIVATION ONLY)
-- ⚠ UNAPPLIED / OFFLINE review artifact. NOT executed against any live database by this packet.
--   AI-STAGING Postgres b7362594-a01b-4623-a982-394707a6cec2 ONLY, under a SEPARATE explicit Owner authorization.
--   NEVER CORE-PROD (project 04c8b523-5b15-4d81-af06-8c2aa1a83499 / Postgres 1fbd7632-95ad-46f3-a20c-5be5b8e44e6b).
-- Generated by m7s1/build-sql.mjs from catalog/v2-digest-gen.mjs (T0=2026-09-28T15:26:23Z); do not hand-edit.
-- Removes ONLY the successor schema + its two functions, and ONLY while no V2 approval has ever been
-- consumed and V2 is exactly inactive. NEVER touches the M6 schema/ledger/functions, NEVER deletes a
-- ledger row, NEVER touches V1/V2 catalog rows (an inactive V2 seed is inert and simply expires at
-- 2026-10-05T15:26:23Z; it is never deleted). After any V2 activation, use restoration (06/07) instead — FAIL CLOSED.
-- ═════════════════════════════════════════════════════════════════════════

\set ON_ERROR_STOP on
BEGIN;
DO $rb$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_namespace WHERE nspname='live_ai_03b_trusted_v2') THEN RAISE EXCEPTION 'successor rollback: schema absent (nothing to roll back)'; END IF;
  IF EXISTS (SELECT 1 FROM live_ai_03b_trusted.approval_consumption WHERE active_catalog_digest IN ('836548ef0274f3a068c83cf4d8e952eb6388921f2064c5e29e8ec25cd7eb798b', '36355fab5be8009fa66352ce678394d4963f2927a39d1a8eea63f4aa5b939b62')) THEN
    RAISE EXCEPTION 'successor rollback: a V2 approval was consumed — use restoration, never remove the boundary (HOLD)'; END IF;
  IF EXISTS (SELECT 1 FROM public.budget_price_catalog_versions WHERE status<>'inactive') OR EXISTS (SELECT 1 FROM public.budget_price_catalog_entries WHERE status<>'inactive') THEN
    RAISE EXCEPTION 'successor rollback: a catalog is active — restore first (HOLD)'; END IF;
  IF (SELECT count(*) FROM pg_proc pr JOIN pg_namespace nn ON nn.oid=pr.pronamespace WHERE nn.nspname='live_ai_03b_trusted_v2') <> 2
     OR EXISTS (SELECT 1 FROM pg_class c JOIN pg_namespace nn ON nn.oid=c.relnamespace WHERE nn.nspname='live_ai_03b_trusted_v2') THEN
    RAISE EXCEPTION 'successor rollback: successor schema holds unexpected objects (HOLD)'; END IF;
END $rb$;
DROP FUNCTION live_ai_03b_trusted_v2.activate_catalog_v2(jsonb, text);
DROP FUNCTION live_ai_03b_trusted_v2.restore_catalog_v2_inactive(jsonb, text);
DROP SCHEMA live_ai_03b_trusted_v2 RESTRICT;
DO $post$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_namespace WHERE nspname='live_ai_03b_trusted_v2') THEN RAISE EXCEPTION 'successor rollback: schema still present'; END IF;
  IF (SELECT count(*) FROM pg_proc pr JOIN pg_namespace nn ON nn.oid=pr.pronamespace WHERE nn.nspname='live_ai_03b_trusted') <> 2 THEN RAISE EXCEPTION 'successor rollback: M6 schema changed'; END IF;
  RAISE NOTICE 'successor rollback OK — M6 boundary + ledger + catalog rows untouched';
END $post$;
COMMIT;
