import assert from 'node:assert/strict';
import { generateKeyPairSync, sign } from 'node:crypto';
import * as G from '../src/v3-digest-gen.mjs';
import { reviewedV3Rows, checkV3Catalog } from '../src/v3-catalog-contract.mjs';
import { buildEvidenceContentV3,evidenceContentDigestV3,buildApprovalPayloadV3,canonicalize,publicKeyFingerprintFromDerB64,toVerifiedClaimsV3,VERIFIED_CLAIMS_KEYS_V3 } from '../src/pricing-approval-contract-v3.mjs';
import { verifyApprovalV3 } from '../src/approval-verify-v3.mjs';
import { runtimePinRef } from '../src/v3-runtime-identity.mjs';
let pass=0; const test=(name,fn)=>{try{fn();pass++;}catch(e){console.error('FAIL',name,e);process.exitCode=1;}};
const clone=x=>JSON.parse(JSON.stringify(x));
test('predecessor digests exact',()=>assert.equal(G.PREDECESSOR_FAILURES.length,0));
test('fresh successor times exact',()=>{assert.equal(G.T0,'2026-10-06T22:44:42Z');assert.equal(G.T0_PLUS_7_DAYS,'2026-10-13T22:44:42Z');});
test('worst case remains 105920',()=>assert.equal(G.V3_WORST_CASE_MICROS,105920));
test('v3 valid inactive before expiry',()=>{const r=reviewedV3Rows('inactive');assert.equal(checkV3Catalog(r.version,r.entries,'inactive','2026-10-07T00:00:00Z').ok,true);});
test('v3 valid active before expiry',()=>{const r=reviewedV3Rows('active');assert.equal(checkV3Catalog(r.version,r.entries,'active','2026-10-07T00:00:00Z').ok,true);});
test('v3 rejects exactly at expiry',()=>{const r=reviewedV3Rows();assert.equal(checkV3Catalog(r.version,r.entries,'inactive',G.T0_PLUS_7_DAYS).reason,'verification_stale');});
test('v3 rejects changed rate',()=>{const r=reviewedV3Rows();r.entries=clone(r.entries);r.entries[0].rate_micros++;assert.equal(checkV3Catalog(r.version,r.entries,'inactive','2026-10-07T00:00:00Z').reason,'rate_mismatch');});
test('v3 rejects changed source',()=>{const r=reviewedV3Rows();r.entries=clone(r.entries);r.entries[0].source_digest='0'.repeat(64);assert.equal(checkV3Catalog(r.version,r.entries,'inactive','2026-10-07T00:00:00Z').reason,'entry_source_or_status');});
test('v3 rejects changed id',()=>{const r=reviewedV3Rows();r.version={...r.version,id:'wrong'};assert.equal(checkV3Catalog(r.version,r.entries,'inactive','2026-10-07T00:00:00Z').reason,'version_identity_or_status');});
const {publicKey,privateKey}=generateKeyPairSync('ed25519');const der=publicKey.export({format:'der',type:'spki'}).toString('base64');const fp=publicKeyFingerprintFromDerB64(der);
const pin=runtimePinRef({contract:'M7V3SuccessorRuntimePreservationBindingV1',parent:G.SUCCESSOR_PARENT_COMMIT,commit:'1'.repeat(40),tree:'2'.repeat(40),runtime_digest:'3'.repeat(64)});
const evContent=buildEvidenceContentV3(G.T0);const evDigest=evidenceContentDigestV3(evContent);const supplied={id:'fresh-v3-evidence-20261006',digest:evDigest,content:evContent};
const payload=buildApprovalPayloadV3({approval_id:'approval-v3-0001',reviewer_public_key_fingerprint:fp,evidence:{receipt_id:supplied.id,content_digest:evDigest,verified_at:G.T0,evidence_expiry:'2026-10-13T20:00:00Z'},scope:{openai_account_ref:'owner-account-ref',openai_project_ref:'staybid-project-ref'},successor_runtime_pin_ref:pin,execution:{execution_id:'execution-v3-0001',issued_at:'2026-10-07T00:00:00Z',not_before:'2026-10-07T00:00:00Z',expiry:'2026-10-07T01:00:00Z'}});
const sig=sign(null,Buffer.from(canonicalize(payload)),privateKey).toString('base64');const env={alg:'ed25519',signature_b64:sig,payload};const trust={pinnedPublicKeyDerB64:der,pinnedFingerprint:fp};const args={envelope:env,trustRoot:trust,suppliedEvidence:supplied,nowIso:'2026-10-07T00:10:00Z',executionId:'execution-v3-0001',isConsumed:()=>false,successorRuntimePinRef:pin};
test('synthetic v3 approval verifies with resolved pin',()=>assert.equal(verifyApprovalV3(args).ok,true));
test('approval blocks unresolved runtime pin',()=>assert.equal(verifyApprovalV3({...args,successorRuntimePinRef:undefined}).reason,'successor_runtime_pin_ref_unresolved'));
test('approval blocks wrong runtime pin',()=>assert.equal(verifyApprovalV3({...args,successorRuntimePinRef:'4'.repeat(64)}).reason,'successor_runtime_pin_ref_mismatch'));
test('approval blocks tamper after signature',()=>{const e=clone(env);e.payload.scope.output_rate_micros=1;assert.equal(verifyApprovalV3({...args,envelope:e}).reason,'signature_invalid_or_untrusted_signer');});
test('approval blocks wrong signer trust root',()=>{const kp=generateKeyPairSync('ed25519');const d=kp.publicKey.export({format:'der',type:'spki'}).toString('base64');assert.notEqual(verifyApprovalV3({...args,trustRoot:{pinnedPublicKeyDerB64:d,pinnedFingerprint:publicKeyFingerprintFromDerB64(d)}}).ok,true);});
test('approval blocks at catalog expiry',()=>assert.equal(verifyApprovalV3({...args,nowIso:G.T0_PLUS_7_DAYS}).reason,'catalog_verification_expired'));
test('approval blocks replay',()=>assert.equal(verifyApprovalV3({...args,isConsumed:()=>true}).reason,'approval_already_consumed_replay'));
test('verified claims exact 36-key shape',()=>{const c=toVerifiedClaimsV3(payload);assert.equal(Object.keys(c).length,36);assert.deepEqual(Object.keys(c).sort(),[...VERIFIED_CLAIMS_KEYS_V3].sort());});
console.log(`core: ${pass} passed, 0 failed`);if(process.exitCode)process.exit(process.exitCode);
