import assert from 'node:assert/strict';import { generateKeyPairSync } from 'node:crypto';
import * as G from '../src/v3-digest-gen.mjs';import { loadRuntimeConfigV3,REQUIRED_ENV } from '../src/v3-runtime-config.mjs';import { publicKeyFingerprintFromDerB64 } from '../src/pricing-approval-contract-v3.mjs';import { QUERIES,REGISTRY_DIGEST,validateRegistry } from '../src/v3-query-registry.mjs';import { ACTIVATE_SQL_V3,makeRestrictedActivationAdapterV3 } from '../src/v3-restricted-activation-adapter.mjs';import { reviewedV3Rows } from '../src/v3-catalog-contract.mjs';import { checkPreActivationState,checkActivatedState } from '../src/v3-runtime-contract.mjs';import { validateRuntimePreservationBinding } from '../src/v3-runtime-identity.mjs';
let pass=0;const test=async(n,f)=>{try{await f();pass++;}catch(e){console.error('FAIL',n,e);process.exitCode=1;}};
const kp=generateKeyPairSync('ed25519');const der=kp.publicKey.export({format:'der',type:'spki'}).toString('base64');const env={ [REQUIRED_ENV.version]:'V3',[REQUIRED_ENV.reviewerDer]:der,[REQUIRED_ENV.reviewerFp]:publicKeyFingerprintFromDerB64(der),[REQUIRED_ENV.project]:'4ad1abb3-823a-4acf-b889-6d34ae46d7f9',[REQUIRED_ENV.environment]:'aa397bd7-b316-4fd8-b05a-0a5f6c5e3abc',[REQUIRED_ENV.pg]:'b7362594-a01b-4623-a982-394707a6cec2',[REQUIRED_ENV.gateway]:'dd96c7cd-02c1-4d02-89eb-7e217930ebfa',[REQUIRED_ENV.connectionRef]:'staybid.live-ai-03b.executor-attester.v2'};
await test('V3 runtime config accepts exact targets',()=>assert.equal(loadRuntimeConfigV3(env).ok,true));await test('V2 runtime version rejected',()=>assert.equal(loadRuntimeConfigV3({...env,[REQUIRED_ENV.version]:'V2'}).reason,'runtime_contract_not_v3'));await test('V1 executor attester issuer rejected',()=>assert.equal(loadRuntimeConfigV3({...env,[REQUIRED_ENV.connectionRef]:'staybid.live-ai-03b.executor-attester.v1'}).reason,'connection_identity_ref_not_executor_attester_v2'));
await test('query registry exact and SELECT-only',()=>{assert.equal(validateRegistry(QUERIES).ok,true);assert.match(REGISTRY_DIGEST,/^[0-9a-f]{64}$/);for(const q of Object.values(QUERIES)){assert.match(q,/^SELECT /);assert.ok(!/;|--|\/\*|\b(UPDATE|DELETE|INSERT|ALTER|CREATE|DROP|LOCK)\b/i.test(q));}});
await test('restricted adapter emits only trusted_v3 fixed SQL once',async()=>{const calls=[];const a=makeRestrictedActivationAdapterV3({dbClient:{query:async(sql,args)=>{calls.push({sql,args});return {rows:[{ok:true}]};}}});const claims={contract:'VerifiedApprovalClaimsV3',execution_id:'execution-v3-0001'};assert.equal((await a.activate({claims,executionId:claims.execution_id})).ok,true);assert.equal(calls[0].sql,ACTIVATE_SQL_V3);assert.equal((await a.activate({claims,executionId:claims.execution_id})).reason,'activation_is_one_shot');});
function obs(status){const v3=reviewedV3Rows(status);return {versions:[{id:G.V1.id,status:'inactive',effective_from:G.V1.t0,effective_until:null,catalog_digest:G.V1.inactive_catalog_digest,created_at:G.V1.t0},{id:G.V2.id,status:'inactive',effective_from:G.V2.t0,effective_until:null,catalog_digest:G.V2.inactive_catalog_digest,created_at:G.V2.t0},v3.version],entries:[...G.entryRows(G.V1.id,G.V1_RATES,G.V1.t0,G.V1.expiry,G.V1.source_digest,'inactive'),...G.entryRows(G.V2.id,G.V2_RATES,G.V2.t0,G.V2.expiry,G.V2.source_digest,'inactive'),...v3.entries],policyRows:[{id:G.DORMANT.policy_id,project_id:'live-ai-03b',status:'inactive',session_money_ceiling_micros:0,session_provider_calls:0,session_execution_admissions:0,subject_day_money_ceiling_micros:0,project_day_money_ceiling_micros:0,project_month_money_ceiling_micros:0,global_day_money_ceiling_micros:0,policy_digest:G.DORMANT.policy_digest}],controlRows:[{scope_type:'global',scope_key_digest:'global',control_epoch:1,enabled:false,killed:false,record_digest:G.DORMANT.control_global_digest},{scope_type:'project',scope_key_digest:'live-ai-03b',control_epoch:1,enabled:false,killed:false,record_digest:G.DORMANT.control_project_digest}]};}
await test('runtime preactivation exact state passes',()=>assert.equal(checkPreActivationState(obs('inactive'),'2026-10-07T00:00:00Z').ok,true));await test('runtime activated exact V3 passes',()=>assert.equal(checkActivatedState(obs('active'),'2026-10-07T00:00:00Z').ok,true));await test('runtime rejects predecessor entry mutation',()=>{const o=obs('inactive');o.entries[0].rate_micros++;assert.equal(checkPreActivationState(o,'2026-10-07T00:00:00Z').reason,'predecessor_not_byte_exact');});
await test('runtime preservation binding is fail-closed/external',()=>{assert.equal(validateRuntimePreservationBinding({contract:'M7V3SuccessorRuntimePreservationBindingV1',parent:G.SUCCESSOR_PARENT_COMMIT,commit:'1'.repeat(40),tree:'2'.repeat(40),runtime_digest:'3'.repeat(64)}).ok,true);assert.equal(validateRuntimePreservationBinding({contract:'M7V3SuccessorRuntimePreservationBindingV1',parent:G.SUCCESSOR_PARENT_COMMIT,commit:G.SUCCESSOR_PARENT_COMMIT,tree:'2'.repeat(40),runtime_digest:'3'.repeat(64)}).reason,'runtime_binding_commit_not_successor');});
console.log(`runtime-static: ${pass} passed, 0 failed`);if(process.exitCode)process.exit(process.exitCode);
